name: Build

on:
  - push


jobs:
  build:
    name: "Build Hugo"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v2
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
      - uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: "Run Hugo"
        run: hugo