name: Build

on:
  - push


jobs:
  build:
    name: "Build Hugo"
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'npm'
      - name: "Setup Hugo"
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.0'
          extended: true
      - name: "Setup cache for Hugo"
        uses: actions/cache@v2
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: "Install the dependencies of the theme"
        run: "cd themes/tournaments/ && npm install && npm run fontawesome && cd ../../."
        shell: bash
      - name: "Test if webfonts is where it should be"
        run: test -d themes/tournaments/static/webfonts
        shell: bash
      - name: "Run Hugo"
        run: hugo
